name: Upload PDF to Mega Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow the workflow to be triggered manually

jobs:
  download-files:
    runs-on: ubuntu-latest
    timeout-minutes: 340  # Timeout after 1 hour (60 minutes)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'



      - name: Install dependencies
        run: |
          sudo apt-get install -y poppler-utils
          pip install -r req.txt
          pip install --upgrade tenacity

          
      - name: Download files from Mega

        run: |

          python file.py
          
